#!/bin/bash -eu

sudo cat <<__EOF__ > /etc/sudoers.d
jsh     ALL=(ALL)       NOPASSWD: ALL
__EOF__
chmod 440 /etc/sudoers.d

sudo dnf update
sudo systemctl start openssh-server
sudo systemctl enable openssh-server
ssh-keygen
cp .ssh/id_rsa.pub .ssh/authorized_keys
chmod 600 $_
sudo dnf install ansible python2-dnf
dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

dnf install gstreamer-plugins-bad gstreamer-plugins-bad-free-extras gstreamer-plugins-bad-nonfree gstreamer-plugins-ugly gstreamer-ffmpeg gstreamer1-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld gstreamer1-plugins-base-tools gstreamer1-plugins-good-extras gstreamer1-plugins-ugly gstreamer1-plugins-bad-free gstreamer1-plugins-good gstreamer1-plugins-base gstreamer1

dnf install dkms kernel-devel
dnf config-manager --add-repo=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
dnf install VirtualBox-5.1
/sbin/rcvboxdrv setup
cd /opt
sudo wget http://download.virtualbox.org/virtualbox/5.1.0/Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack
sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack

dnf install vlc # video
dnf install ffmpeg libavdevice # mp3s

git clone git@github.com:jsh/dotfiles
cp -a dotfiles/.bash* .
cp -a dotfiles/.vimrc .
